### PR TITLE
update dgraph latest version

### PR DESCRIPTION
**Pull request by Ro0tk1t**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/ratel/241)

 

Ratel Preview: [Dgraph Preview](https://dgraph-ratel-76b2f8ca1df7321-114543.surge.sh/?local)

### CODE REVIEW

**Review by MichelDiz — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/ratel/241#-:-MOsVs0x56ery-inNu7Q:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Ro0tk1t)

**Review by Ro0tk1t — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/ratel/241)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Ro0tk1t)

**Review by Ro0tk1t — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/ratel/241#-:-MOsc4KwE2fGuURlNcYS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Ro0tk1t)

**Comment by MichelDiz** [comment]
@Ro0tk1t you don't need review your own PR.

**Comment by Ro0tk1t** [comment]
sorry, but i see  waiting on me

**Comment by MichelDiz** [comment]
I see, please ignore it. That information is wrong. Only us are need to review, the sender don't.
Cheers.

**Review by danielmai — APPROVED** [review]
Thanks for your PR, @ro0tk1t! :lgtm: 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/ratel/241#-:-MP4xWi93NIZ6DlHa3C6:b4qaz4e)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Ro0tk1t)

**Pull request merged**
