### PR TITLE
Add backup and restore option

### PR DESCRIPTION
**Pull request by Vikash13**
Completed with following-
- Layout and Navigation
- UI Component design
- Bound with mock data

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/ratel/83)

### CODE REVIEW

**Comment by Vikash13** [comment]
Here is task breakdown
- [x] Layout and navigation
- [x] UI component design, binding with mock data
- [x] Create backup API integration
- [ ] Backup list/delete/restore API integration
- [ ] Error handling / Control validation
- [ ] Unit testing
- [ ] E2E testing
- [ ] UI issues across other pages

**Comment by Vikash13** [comment]
Currently, we have the prototype with mock data.

- No, I have not removed all the dummy once but will do so in the same PR. Currently, backup creation is working well end to end. Will clean the code base.

- Showing the backup list would be a more relevant feature but currently, it is not supported by the backend.

We also have to address the following workflow issues -

1. We have two basic operation - Create Backup / Restore Backup. If anyone of the operations takes longer time and the user refreshes the page and launch it again as we are not persisting the state of the current operation, it will create a new request even though the previous one is not yet finished. Or Using any rest client (postman) you can hit the endpoint multiple times.

2. How do we handle Backup and Restore while one is going on? We should block the request of other operation when any one of the operations is going on, as they are mutually exclusive. 

**My suggestions:**

1. We should maintain the state of the operation that is being performed. User can refresh the page to see what is going on. e.g. If a user performs a backup operation, it will have a status like InProgress, Success, Failed that will be coming from backend API.

2. Instead of Backup list, we can show Timeline history

| Started At                      |  End At                          | Event type     | Status    | Size        | Path   |Remarks|
| -----------------------| -----------------------|-------------|----------| ---------| ------|-------- |
| 05/14/2019 11:00 AM   | 05/14/2019 11:20 AM   | Backup         | InProgress       |                |/usr/a |
| 05/04/2019 4:00 PM   | 05/04/2019 5:20 AM   | Restore         | Done       | 200 mb  |/usr/a  |
| 05/03/2019 4:00 PM   | 05/03/2019 5:20 AM   | Backup         | Failed       |               | /x/b     |

Whenever there is user action, we would be capturing them and updating them asynchronously.

**Mockup gif**

demo

**Comment by Vikash13** [comment]
@paulftw 
I am done with the changes. We have Backup creation end to end working and the backup list is being stored in local storage.

**Testing Status:** 
I have tested with Local directory backup, but couldn't test for Amazon S3, Minio or NFS as I don't have the setup locally.

FYI: @manishrjain @mangalaman93

**Comment by paulftw** [comment]
hey @Vikash13 just checking, are you getting email notifications when someone leaves a comment on reviewable?

**Comment by Vikash13** [comment]
Yes @paulftw. I'm getting the notification.

**Pull request closed without merging**
