### PR TITLE
Upgrade all scripts to the latest

### PR DESCRIPTION
**Pull request by MichelDiz**
Using create-react-app, I upgraded all the main configuration files and scripts.
In other words, I'm removing legacy code.

PS. Everything is working fine, just the CDN that I’m not so sure about. If it will break.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/ratel/238)

 
 
 
 
 
 
 
 

Ratel Preview: [Dgraph Preview](https://dgraph-ratel-3d9266afb7b7315-118759.surge.sh/?local)

### CODE REVIEW

**Comment by gja** [comment]
This looks fine at a surface level, but a few questions:
1) Why can't we stay on NPM? I really don't like yarn.
2) Can you explain the steps you took here? The PR is way to huge to review line by line (though most changes look benign)

**Comment by MichelDiz** [comment]
@gja 
1. There is a dependency conflict, but you can use `npm cache clean --force` and `npm install --legacy-peer-deps` that will work fine. Yarn solve this internally without prompt anything.
The dependency conflicts are in third-party deps.
2. What I did is, inspect all dependencies used in the repo. Create a new "Create React app", migrate all configs and the folder src to the new CRA. Then I started the client, also run the tests and also check the tests in TC. All fine.

**Comment by gja** [comment]
Even still. One random issue is not a good reason to abandon npm. Please stick to npm everywhere.

**Comment by MichelDiz** [comment]
I can't do anything if third party don't upgrade their deps - It is not a choice. Thats the issue of using third party dependencies. We have to rely in their work, trust that they will keep updated, that they won't add security issues.

Or we remove as much deps we can, or we force it. Really, there's no issue there.

About NPM vs YARN, not sure why you would not like it. It is faster, solve issues on the fly, run in parallel. I personally use it for a long time and rarely it fail to me. NPM otherwise, all the time it has an issue to solve. For me it is just a personal taste, there is not a problem in fact.

**Review by gja — APPROVED** [review]

**Pull request merged**
