### PR TITLE
replaced the graphql and graphql+- endpoints

### PR DESCRIPTION
**Pull request by antblood**
changed the graphql and graphql+- endpoints

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/ratel/234)

 
 

Ratel Preview: [Dgraph Preview](https://dgraph-ratel-cb29087a7d17664-93671.surge.sh/?local)

### CODE REVIEW

**Review by danielmai — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/ratel/234)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @antblood and @danielmai)

___
*[server/play-dgraph-io.nginx.conf, line 22 at r2](https://reviewable.io/reviews/dgraph-io/ratel/234#-MHHwq1b5USqNocC9PYD:-MHHwq1b5USqNocC9PYE:b3cmmm7) ([raw file](https://github.com/dgraph-io/ratel/blob/cb29087a7d17664248ed05834b02763b0feb36b3/server/play-dgraph-io.nginx.conf#L22)):*
> ```
>     proxy_pass https://crooked-advertisement.us-west-2.aws.cloud.dgraph.io;
>     proxy_set_header X-Auth-Token rFixJ0UBTQrtoyF8ZWA4ChoaGjqPthPGFtrofqvVB6g=;
> ```
Should there be two endpoints? I thought we were aiming to have one.

**Review by danielmai — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/ratel/234#-:-MHHxUBO2SgPZkrFDFfn:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @antblood)

**Review by antblood — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/ratel/234)* status: all files reviewed, 1 unresolved discussion (waiting on @danielmai)

___
*[server/play-dgraph-io.nginx.conf, line 22 at r2](https://reviewable.io/reviews/dgraph-io/ratel/234#-MHHwq1b5USqNocC9PYD:-MHI1kxK0W7W7ZSlLjNd:b-nnxce0) ([raw file](https://github.com/dgraph-io/ratel/blob/cb29087a7d17664248ed05834b02763b0feb36b3/server/play-dgraph-io.nginx.conf#L22)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
>     proxy_pass https://crooked-advertisement.us-west-2.aws.cloud.dgraph.io;
>     proxy_set_header X-Auth-Token rFixJ0UBTQrtoyF8ZWA4ChoaGjqPthPGFtrofqvVB6g=;
> ```
Should there be two endpoints? I thought we were aiming to have one.
</blockquote></details>

two will work.

**Review by antblood — COMMENTED** [review]
:+1: 

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/ratel/234#-:-MHI1zERBLSThZH0I-gd:b-8fx2u7)* status: all files reviewed, 1 unresolved discussion (waiting on @danielmai)

**Pull request merged**
